version: '3'
services:
    frontend-nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/frontend/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    frontend-nodejs:
        image: node:10.10
        volumes:
            - ./:/var/www
        working_dir: /var/www/frontend
        tty: true
    api-nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/api/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "81:80"
        depends_on:
            - api-php-fpm
    api-php-fpm:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./docker/storage/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=piplos"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8097:8080