home:
    path:   /
    controller: App\Controller\SiteController::index
contacts:
    path:   /contacts
    controller: App\Controller\ContactController::index
product:
    path:   /{slug}.html
    controller: App\Controller\Catalog\ProductController::product
category:
    path:   /{slug}
    controller: App\Controller\Catalog\ProductController::category
